### ISSUE TITLE
Created tokens, collectibles and metadata, same dog every time, and not visible on OpenSea

### ISSUE THREAD

**Issue by AnneCh** [PatrickAlphaC/nft-demo#10]
Hi! 

I'm at the end of lesson 11, when we test all our scripts on Rinkeby.

I've successfully deployed and created new collectibles, I have 3uint256 in my 
tokenCounter on Etherscan, but when creating the metadata json files, I see that the three of them are PUG dogs. Is it normal?

Secondly, on OpenSea, after more than an hour waiting and refreshing the page, the dog pictures are not visible and their name is all the same : [Dogie - lmUs6d9XtY on OpenSea](https://testnets.opensea.io/collection/dogie-lmus6d9xty), [my contract's Etherscan page](https://rinkeby.etherscan.io/address/0x2c53cE22D0c854740B8756C7917640D78F511Ab8#events)

I'm not really sure which code to share that would give you relevant information to try to help, so feel free to ask and I'll add to this post.

All the images are correctly named in an _img_ folder, the _rinkeby_ folder is correctly inside the metadata folder

**Comment by PatrickAlphaC** [comment]
Close. Your `tokenURI` is returning an _image_ of the dog, but it needs to return _metadata including the image of the dog_.

If you go to your contract page: https://rinkeby.etherscan.io/address/0x2c53cE22D0c854740B8756C7917640D78F511Ab8#readContract and go to read the result of `tokenURI` of tokenId 0, what do you get? You get the _image_ of the dog. You need that to be the token metadata. 

You see this file: https://youtu.be/M576WGiDBdQ?t=42226

That's what you want it to return.
<img width="1010" alt="Screen Shot 2022-01-17 at 6 35 05 PM" src="https://user-images.githubusercontent.com/54278053/149847739-4cc3b151-31a2-47ab-8e35-61fbc48b90c7.png">

**Comment by AnneCh** [comment]
Thanks @PatrickAlphaC , I'm not sure where I went wrong but I'll dig and find out!
