### ISSUE TITLE
Couldn't import LinkToken or VRFCoordinatorMock from brownie

### ISSUE THREAD

**Issue by snowyaya** [PatrickAlphaC/nft-demo#16]
Hi,
I am trying to run the `advanced_collectible` `deploy_and_create.py`, but cannot import `LinkToken` or `VRFCoordinatorMock` from brownie. 
This is the command line I am using. 
`brownie run scripts/advanced_collectible/deploy_and_create.py`

Any suggestions?

**Comment by PatrickAlphaC** [comment]
Thanks for this issue! Could you please make it on the larger overall repo? Thanks! 
https://github.com/smartcontractkit/full-blockchain-solidity-course-py
