### ISSUE TITLE
Cannot see metadata on opensea

### ISSUE THREAD

**Issue by Squallaz** [PatrickAlphaC/nft-demo#19]
Hi guys, if i go to https://testnets.opensea.io/assets?search[query]=0xeFfc5d2E70d0961D35e94cee63f87203000a36A9 i can see that i minted two items from my contract but i cannot see the metadata even after hours.

In my python script, if i run print(advanced_collectible.tokenURI(token_id)) i can see all the metadata links: 

- https://ipfs.io/ipfs/Qmd9MCGtdVz2miNumBHDbvj8bigSgTwnr4SbyH6DNnpWdt?filename=0-PUG.json
- https://ipfs.io/ipfs/QmbBnUjyHHN7Ytq9xDsYF9sucZdDJLRkWz7vnZfrjMXMxs?filename=2-ST_BERNARD.json

so i suppose that the metadata  field has been wrote on the chain.
Any idea on why i cannot see the metadata on opensea?

thank you and cheers from Italy

**Comment by PatrickAlphaC** [comment]
Opensea has been slow recently with the Yuga Labs mint. 

Everything looks correct to me. You'll also need to remember to hit "refresh metadata" on the token's page.
