### ISSUE TITLE
Cannot import LinkToken from brownie

### ISSUE THREAD

**Issue by JayAlwaysCodes** [PatrickAlphaC/nft-demo#21]
![linkerr](https://user-images.githubusercontent.com/90992687/172522422-ff263fe8-bc95-498b-b9e8-1a113f9b4ae4.PNG)
please how do i solve this error

**Comment by PatrickAlphaC** [comment]
You need the test folder with the link token in it.

https://github.com/PatrickAlphaC/nft-demo/tree/main/contracts/test

Please refer to here for formatting issues in the future, thank you! 
https://www.youtube.com/watch?v=XT8STflvwNo
