### ISSUE TITLE
Did you also have problems with verifying your code?

### ISSUE THREAD

**Issue by FBosler** [PatrickAlphaC/nft-demo#4]
Looking at the repo it seems like you also tried to manually flatten the contract. Also see [here](https://github.com/eth-brownie/brownie/issues/1345)

I ended up flattening the contract via remix and was able to upload the flattened .sol file, but that is horribly cumbersome. Did you somehow manage to solve this?

**Comment by PatrickAlphaC** [comment]
Don't do the manual flattening, it's pretty bad. 

We got brownie to fix its verification!! Everything in here should work properly now: https://matnad.medium.com/how-to-verify-your-brownie-project-on-etherscan-82d6086644cf

**Comment by FBosler** [comment]
thx @PatrickAlphaC! Appreciate the response and the work you are doing.

I had read the article you mentioned, didn't really help though. You can also have a look at the following ([replicable](https://github.com/FBosler/brownie_verification_error)) issue I raised directly with brownie. [Issue here](https://github.com/eth-brownie/brownie/issues/1345)

Cheers sir

**Comment by PatrickAlphaC** [comment]
Hmm... I'm able to verify successfully. Perhaps your API key is off?
