### ISSUE TITLE
Advanced NFT always breed 1

### ISSUE THREAD

**Issue by izamzam2020** [PatrickAlphaC/nft-demo#8]
Hi,

I'm following along with the tutorial for the advanced NFT and it looks like every time the code is being run the breed is always 1.

I have copied the codebase from the git repo to be sure and the result is still the same, the contract address is 0xfB372045283C46E134042794c37A87FfA3e48B73

Any ideas what maybe happing would be helpful, I'd be surprised if the VRF gave me the same result 4 times.

Thanks

**Comment by PatrickAlphaC** [comment]
The script probably just isn't waiting long enough, extend the `sleep` to be 4 times as long.
