### ISSUE TITLE
Why this one cannot be verified on Etherscan Rinkeby Testnet

### ISSUE THREAD

**Issue by DanteYcY** [PatrickAlphaC/nft-demo#9]
Hi!

I just finished deploying the AdvancedCollectible.sol
Everything went well, except I couldn't verify the deployed contract on Etherscan directly.
Here's the address of the contract: https://rinkeby.etherscan.io/address/0x0Dc3dF23EF61C608F819487C6E17C41C32F7dA28
My solidity compiler version is 0.8.0. I'm not sure if that matter. Everything else stays alone with the video content.
I tried to add the ETHERSCAN_TOKEN in .env and set rinkeby: verify: True in brownie-config.
But it still couldn't be verified like Patrick showed in the video (10:50:20).
Anyone has any idea about this?
Is that because of my code or etherscan?
Thanks in advance!

**Comment by DavidWilliamsQA** [comment]
I was about to ask this question too. Mine doesn't seem to verify too.

**Comment by PatrickAlphaC** [comment]
Can you try the following:

1. Enter a rinkeby brownie shell
```
brownie console --network rinkeby
```
2. Get the contract in the shell and verify

```
contract = AdvancedCollectible.at("0x0Dc3dF23EF61C608F819487C6E17C41C32F7dA28")
AdvancedCollectible.publish_source(contract)
```

This should do it. 

Closing, let me know if that doesn't work.

**Comment by DanteYcY** [comment]
> 
It works.
Thanks a lot! 
I think I made a stupid mistake that I forgot to use publish_source.

**Comment by DavidWilliamsQA** [comment]
@PatrickAlphaC it still seems to not be verifying for me 
![image](https://user-images.githubusercontent.com/60790661/149623329-1e305fdf-bc9b-490a-8c3e-122895008f1e.png)
